name: Debian Build Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:bullseye-slim # Using Debian Bullseye as an example

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install required packages
      run: |
        apt update
        apt install -y sudo build-essential make clang llvm m4 libpcap-dev libelf-dev gcc-multilib cmake

    - name: Run make
      run: make
