name: Debian Build Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:bookworm-slim

    steps:
    - name: Setup Git
      run: |
        apt update
        apt install -y git

    - name: Checkout code with submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache apt packages
      uses: actions/cache@v2
      with:
        path: /var/cache/apt/archives/
        key: apt-packages-${{ runner.os }}

    - name: Install required packages
      if: steps.cache-apt.packages.cache-hit != 'true'
      run: |
        apt install -y sudo build-essential make clang llvm m4 libpcap-dev libelf-dev gcc-multilib cmake bpftool
        
    - name: Run make
      run: make
